version: '3'
services:
  app:
    container_name: boto_app
    build:
      context: ./php
    volumes:
      - './app/:/var/www/html'
      - './sites:/etc/apache2/sites-enabled'
    links:
      - db
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    ports:
      - 80:80
    networks:
      app_net:
        ipv4_address: 192.16.1.12

  db:
    container_name: boto_db
    image: 'mysql:5.7'
    volumes:
      - './base:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boto
      MYSQL_USER: boto
      MYSQL_PASSWORD: boto
    ports:
      - 13306:3306
    networks:
      app_net:
        ipv4_address: 192.16.1.13
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.16.1.0/24

